export default function Head() {
  return (
    <>
      <title>Lymei | Felipe Cardoso</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta content="Lymei.art" property="og:title"/>
    </>
  )
}
